name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0
      - name: Megalinter
        uses: oxsecurity/megalinter@d8612e7786f5c64747a73759d8bc459224a00fe9 # v6.15.0
        env:
          APPLY_FIXES: "none"
          BASH_SHFMT_DISABLE_ERRORS: "false"
          DISABLE_LINTERS: MARKDOWN_MARKDOWN_LINK_CHECK,REPOSITORY_CHECKOV,REPOSITORY_SECRETLINT,REPOSITORY_TRIVY,SPELL_CSPELL
          FILTER_REGEX_EXCLUDE: .*/ISSUE_TEMPLATE/.*
          FLAVOR_SUGGESTIONS: "false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JSON_PRETTIER_DISABLE_ERRORS: "false"
          LOG_LEVEL: WARN
          MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: "false"
          PRINT_ALL_FILES: "false"
          PRINT_ALPACA: "false"
          SHOW_ELAPSED_TIME: "true"
          SPELL_MISSPELL_DISABLE_ERRORS: "true"
          VALIDATE_ALL_CODEBASE: "true"
          YAML_PRETTIER_DISABLE_ERRORS: "false"
      - name: Artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
        with:
          name: artifacts
          path: |
            report
            mega-linter.log
