name: release

on:
  workflow_dispatch:

permissions: read-all

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  bump:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Install cocogitto
        uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
        with:
          install-only: true
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Bump version
        run: cog --config .github/release/cog.toml bump --auto
      - name: Push commit and tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          git push --atomic origin main "${TAG}"
